### ISSUE TITLE
Milestone 2 release checklist

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/stacks-pyth-bridge#12]
Onchain
- [x] Review of current functional scope
- [x] Agreement on keypairs deploying the contracts and handling maintenance and upgrades (features, fixes)  
- [x] Agreement on developer fee strategy. Is milestone 2 exempted of developer fees (≠ transaction fee), meaning developers can consume price feeds in a free fashion
- [x] Agreement on Smart contract audit process (`wormhole-core` + `pyth`)

Offchain  
- [x] Agreement on who is running and funding relaying operations

**Comment by diwakergupta** [comment]
Thanks @lgalabru 

Can you elaborate on the fee strategy bullet? What's involved in consuming the price feeds from a developer point of view?

Likewise, could you expand on the "relaying operations" piece -- exactly what's involved there in terms of running some infra and / or funding some operations?

**Comment by lgalabru** [comment]
All of the items above are resolved, I'll close this issue.
